# server:
#  port: 8000
#  8080 for jenkins

spring:
  profiles:
    active: prod
    include: prod, test
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    database: mysql
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/bankalgo?serverTimeZone=Asia/Seoul
#    username: bankalgo
#    password: 1234
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
