spring:
  profiles:
    value: test
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bankalgo_test?serverTimeZone=Asia/Seoul
    name: bankalgo_test
    username: bankalgo
    password: 1234